### ISSUE TITLE
Difficulties running the application

### ISSUE THREAD

**Issue by JPT580** [vivo-community/VIVO-Harvester#14]
I ran into some issues trying to get this software to run - even though maven threw some warnings about library dependencys with system scope, building worked.
While installing the .deb package with dpkg -i (That command points to bin/ instead of build/ in update-rebuild-install.sh), i got warnings about the postinstall script trying to chgrp/chown to tomcat6 (I am on debian with tomcat7, there is no tomcat6 user or group).

Trying to make the harvester-\* commands work, i found that i had to alter the java command using -cp harvester.jar:dependency/\* in order to get them running from within /usr/share/vivo/harvester/bin.

Since i did not find detailed installation instructions, i assume that it might be a good idea to add some to the readme file?
I might have missed some things, so please point them out.

**Comment by hauschke** [comment]
Can be closed. I was part of that project, it's no longer relevant.

**Comment by JPT580** [comment]
Yes, that issue is way too old now. I'll close it. :-)
